# Generated by Django 5.1.5 on 2025-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
