# Generated by Django 5.1.5 on 2025-01-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverseapp', '0002_alter_designs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='tag',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('metal', 'Metal'), ('pop', 'Pop'), ('anime', 'Anime'), ('minimals', 'Minimals'), ('cartoon', 'Cartoon'), ('fiction', 'Fiction')], max_length=25),
        ),
    ]
