# Generated by Django 5.1.5 on 2025-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverseapp', '0003_alter_designs_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('heading', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('price', models.CharField(max_length=250)),
                ('cat', models.CharField(choices=[('trending', 'Trending'), ('thrifted', 'Thrifted')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
